@controller=http://localhost/indihome/pelanggan

GET {{controller}}/get/1 HTTP/1.1
Content-Type: application/json

###
POST {{controller}}/add HTTP/1.1
Content-Type: application/json

{
  "kodepelanggan": "001322555",
  "nama": "Bagus Joko Susilo",
  "kontak": "0967623321",
  "alamat": "Aryoko",
  "email": "bagus@mail.com"
}

###

PUT {{controller}}/update HTTP/1.1
Content-Type: application/json

{
  "id": "1",
  "kodepelanggan": "001321522",
  "nama": "Deni Malik",
  "kontak": "0967553124",
  "alamat": "Perum Pemda II",
  "email": "deni@mail.com"
}

###

DELETE {{controller}}/delete/2 HTTP/1.1